title = "Bryce Kwon's Website"
baseURL = "https://www.brycekwon.com"
languageCode = "en-us"

minify = true
enableRobotsTXT = true
disableHugoGeneratorInject = true
disableKinds = ["taxonomy", "term", "rss"]

[markup]
    [markup.highlight]
        lineNos = true
        lineNumbersInTable = false
        style = "catppuccin-macchiato"
    [markup.goldmark]
        [markup.goldmark.renderer]
            hardWraps = true
        [markup.goldmark.parser]
            wrapStandAloneImageWithinParagraph = false

[params]
    [params.author]
        name = "Bryce Kwon"
        email = "b0d1d384838282d4809d8682d5809d8489d6809dd28584869d8384d58882d686d5d1838087f0c3d9ddc0dcd5dcdfd7d9de9ed3dfdd"

# [[menu.main]]
# name = "About"
# url = "/"
# weight = 10

[[menu.social]]
name = "GitHub"
pre = "github"
url = "https://github.com/brycekwon"
weight = 10

[[menu.social]]
name = "LinkedIn"
pre = "linkedin"
url = "https://www.linkedin.com/in/brycekwon"
weight = 20
